twist_mux:
  ros__parameters:
    use_stamped: false          # or true, if your input topics publish TwistStamped
    cmd_vel_out: "/cmd_vel_raw"
    topics:
      teleop:
        topic: "/cmd_vel_teleop"
        timeout: 0.5
        priority: 20
      nav:
        topic: "/cmd_vel_nav"
        timeout: 0.5
        priority: 10

