twist_mux:
  ros__parameters:
    output_topic: "/cmd_vel_raw"
    priority_drivers:
      - name: teleop
        topic: "/cmd_vel_teleop"
        timeout: 0.5
        priority: 20
      - name: nav
        topic: "/cmd_vel"
        timeout: 0.5
        priority: 10
