output_topic: "/cmd_vel_nav"
priority_drivers:
  - name: teleop
    topic: "/cmd_vel_teleop"
    timeout: 0.5
    priority: 20
  - name: teleop_fallback
    topic: "/cmd_vel"
    timeout: 0.5
    priority: 20
  - name: nav
    topic: "/cmd_vel_nav_raw"
    timeout: 0.5
    priority: 10
