twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: "/cmd_vel_teleop"
        timeout: 0.5
        priority: 20
      nav:
        topic: "/cmd_vel"
        timeout: 0.5
        priority: 10
    output_topic: "/cmd_vel_raw"

