waypoints:
  - lat: 34.065982612852416
    lon: -106.90791934172131
    yaw_deg: 0.0
  - lat: 34.06596095803971
    lon: -106.90758710130524
    yaw_deg: 0.0
  - lat: 34.06597289795391
    lon: -106.90720542242926
    yaw_deg: 180.0
  - lat: 34.06597400178699
    lon: -106.9067809617728
    yaw_deg: 0.0
  - lat: 34.066136069860605
    lon: -106.90666755884814
    yaw_deg: 0.0
